s3BucketFiles:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:app}-${self:provider.stage}-files
    CorsConfiguration:
      CorsRules:
        -
          AllowedOrigins:
            - '*'
          AllowedHeaders:
            - '*'
          AllowedMethods:
            - GET
            - PUT
            - POST
            - DELETE
            - HEAD
          MaxAge: 3000
          ExposedHeaders:
            - 'ETag'