productInsertACL:
  handler: product/productFunction/js/productInsertACL.productInsertACL
  environment:
    stage: ${self:provider.stage}
  events:
    - http:
        path: ${self:app}-product/acl/save
        method: POST
        integration: lambda
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: apiGatewayAuthorizer
        cors: true   
